### ISSUE TITLE
Throws error when paradigm4 repos are installed

### ISSUE THREAD

**Issue by ksens** [Paradigm4/extra-scidb-libs#1]
@JAKinchen 

I have a VM where I have the following installed

```sh
apt list | grep paradigm4-18.1-all-c

# paradigm4-18.1-all-coord/unknown,now 2-1 amd64 [installed]
```

On this machine, I tried installing the plugins via this repo

```sh
wget https://github.com/Paradigm4/extra-scidb-libs/raw/master/extra-scidb-libs-18.1-0.deb
sudo gdebi extra-scidb-libs-18.1-0.deb 
```
... but got an error

```sh
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Building data structures... Done 
Building data structures... Done 
This package is uninstallable
Dependency is not satisfiable: scidb-18.1-all-coord
```

**Comment by rvernica** [comment]
Is there a specific reason for `extra-scidb-libs` to depend on `scidb-VERSION-all` or `scidb-VERSION-all-coord` as opposed to just depend on `scidb-VERSION`?

**Comment by rvernica** [comment]
Also, is there a reason why there is no dependency declared for the `.rpm` package?

**Comment by ksens** [comment]
@rvernica 

Yes, `scidb-VERSION` is the right dependency to add. 

I reopened the ticket -- this might be a good time to add the dependency for `.rpm` package at this point. It was probably just missed out. 

Close the ticket if you have already done so.

**Comment by rvernica** [comment]
Dependency for the `.rpm` package was actually added in 6762938a79ff098ffdad4127e876a9c719049305. I forgot to tag the commit with the issue number.

**Comment by ksens** [comment]
👍
