### ISSUE TITLE
New tag naming strategy

### ISSUE THREAD

**Issue by ksens** [Paradigm4/extra-scidb-libs#13]
@rvernica 

Following tag changes are requested to keep in line with the [P4-CS branch / tag naming strategy](https://github.com/Paradigm4/extra-scidb-libs/blob/master/branch-tag-naming-strategy.md). 

A. Tag `rel18.1.1` must be renamed to strategy `vXX.YY.Z`

- [x] [`grouped_aggregate`](https://github.com/Paradigm4/grouped_aggregate/tags)
- [x] [`accelerated_io_tools`](https://github.com/Paradigm4/accelerated_io_tools/tags)
- [x] [`equi_join`](https://github.com/Paradigm4/equi_join/tags)
- [x] [`superfunpack`](https://github.com/Paradigm4/superfunpack/tags)

B. Appropriate `vXX.YY.Z` tags need to be added for:

- [x] [`stream`](https://github.com/Paradigm4/stream/tags)

C. Correcting incorrect tags

- [x] `accelerated_io_tools`: Tag `v15.7` collides with branch `v15.7` and must be removed

**Comment by rvernica** [comment]
I updated the listed repositories. I also updated [shim](https://github.com/Paradigm4/shim/tags) tags. Finally, I updated the numbering to start at `0`, e.g., `v18.1.0`. This numbering is consistent with the one already used in shim and extra-scidb-libs (tags and `.rpm`/`.deb` packages).

**Comment by ksens** [comment]
Awesome! Thanks.
