### ISSUE TITLE
Shim has empty SciDB version, breaks SciDBR

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/extra-scidb-libs#15]
`shim` included in `extra-scidb-libs` `18.1.2` has empty SciDB version:
```bash
> apt-cache show extra-scidb-libs-18.1
Package: extra-scidb-libs-18.1
Version: 2
...
> shim -version
SciDB Version: 
Shim Commit: a19d256
```
This will at least break SciDBR which [expects](https://github.com/Paradigm4/SciDBR/blob/3f19caed86883d55cd4e0027b3f4d7ffe44a7002/R/utility.R#L169) a non-empty version string. When a connection with a username and a password is attempted, SciDBR will error with:
```R
> scidbconnect(username="foo", password="bar")
Error in if (password_digest) attr(db, "connection")$password = base64_encode(digest(charToRaw(password),  : 
  missing value where TRUE/FALSE needed
```
The missing `TRUE/FALSE` value is [password_digest](https://github.com/Paradigm4/SciDBR/blob/3f19caed86883d55cd4e0027b3f4d7ffe44a7002/R/utility.R#L169)

**Comment by ksens** [comment]
Thanks @rvernica - I had noticed this while testing `extra-scidb-libs` on Friday, but was not sure if I was doing something wrong.
