### ISSUE TITLE
extra-scidb-libs overwrites shim config file

### ISSUE THREAD

**Issue by ksens** [Paradigm4/extra-scidb-libs#31]
@JAKinchen @rvernica 

Previously, we had decided that if there is an existing shim config file, shim install should not overwrite it.

Current version of extra-scidb-libs overwrites shim config file.

**Comment by rvernica** [comment]
It appears that during the service changes in Shim, the configuration file was changed from a static file to a [dynamic file](https://github.com/Paradigm4/shim/blob/master/init.d/setup-conf.sh ) re-generated each time the package is [installed](https://github.com/Paradigm4/shim/blob/22ed205c5496441f0d83f97c273786c220a9eed9/init.d/after-install.sh#L7)

**Comment by ksens** [comment]
@rvernica 

Thanks for investigating this. 

A related thought -- I would suggest the following:

By default, the shim config file should have the following :

```
aio=1
```

**Comment by dgosselin-p4** [comment]
@ksens I disagree.  With that change, the shim would depend on accelerated IO tools out-of-the-box.  Unless it can be supported as an extra-scidb-libs change only; then that would be fine.

**Comment by rvernica** [comment]
I think I can add a branch in the `setup-conf.sh` script to check if the file exists. If the file exists it could skip re-writing it.

**Comment by rvernica** [comment]
With the [latest](https://github.com/Paradigm4/shim/commit/8b4505942cdbe1985c395e7c662da205455f1b2b) fix in Shim, you should see the following if the configuration file or the certificate file exist when installing the extra-scidb-libs package:
```
...
Running transaction
  Installing : extra-scidb-libs-19.11-_-1.x86_64                            1/1 
/var/lib/shim/conf file exists, skip re-creating it.
/var/lib/shim/ssl_cert.pem file exists, skip re-creating it.
  Verifying  : extra-scidb-libs-19.11-_-1.x86_64                            1/1 

Installed:
  extra-scidb-libs-19.11.x86_64 0:_-1                                           
```
I tested this locally. This fix will be included in the next release of Shim and the next release of extra-scidb-libs. Unless explicitly requested, we can hold off on making the new release until we accumulate more fixes.
