### ISSUE TITLE
Installing extra-scidb-libs-19.11-5 gives arrow error

### ISSUE THREAD

**Issue by ksens** [Paradigm4/extra-scidb-libs#33]
@rvernica @martin-resnick 

I am getting an error when trying to install `extra-scidb-libs-19.11-5`.

```sh
yum --enablerepo=paradigm4-19p11-extra install extra-scidb-libs-19.11
```

where the hand created repo file looks like below:

```
# content of /etc/yum.repos.d/paradigm4-19p11-extra.repo pasted below
[paradigm4-19p11-extra]
name=Paradigm4 extra libs repository
baseurl=https://downloads.paradigm4.com/extra/19.11/centos7/
enabled=0
fastestmirror_enabled=0
gpgcheck=0
skip_if_unavailable=1
```

The `yum install` command yields:

```
Loaded plugins: amazon-id, jnj-amazon, rhui-lb, search-disabled-repos
Repository pgdg93 is listed more than once in the configuration
Resolving Dependencies
--> Running transaction check
---> Package extra-scidb-libs-19.11.x86_64 0:5-1 will be installed
--> Processing Dependency: arrow-libs < 0.17.0-1 for package: extra-scidb-libs-19.11-5-1.x86_64
--> Processing Dependency: arrow-libs >= 0.16.0-1 for package: extra-scidb-libs-19.11-5-1.x86_64
--> Running transaction check
---> Package arrow-libs.x86_64 0:0.9.0-1.el6 will be installed
---> Package extra-scidb-libs-19.11.x86_64 0:5-1 will be installed
--> Processing Dependency: arrow-libs >= 0.16.0-1 for package: extra-scidb-libs-19.11-5-1.x86_64
--> Finished Dependency Resolution
Error: Package: extra-scidb-libs-19.11-5-1.x86_64 (paradigm4-19p11-extra)
           Requires: arrow-libs >= 0.16.0-1
           Installing: arrow-libs-0.9.0-1.el6.x86_64 (paradigm4-19p11-extra)
               arrow-libs = 0.9.0-1.el6
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Is it because the arrow dependencies are not uploaded to https://downloads.paradigm4.com/extra/19.11/? Or do I need to tweak the repo file?

**Comment by apoliakov** [comment]
Kriti: there was an update to arrow recently.
Try uninstalling libarrow0.9.0 first?

If that fails - Rares - please prioritize this. This might bite us at other
installations.

**Comment by rvernica** [comment]
With your current repository setup, `yum` can't find `arrow-libs >= 0.16.0-1`. In the past, we have rolled-out our own version of `arrow-libs` and served it from the Paradigm4 repository. With the latest version of `extra-scidb-libs` we don't need to do that. As a consequence you need to have the `arrow-libs` repository configured in your setup.

The best way to get the `arrow-libs` repository configured is to use the install script as documented at https://paradigm4.github.io/extra-scidb-libs/
```
wget -O- https://paradigm4.github.io/extra-scidb-libs/install.sh | sudo sh
```
If you still encounter problem try removing the old `extra-scidb-libs-19.11` and `arrow-libs` packages first then retry the install script.

If you want to manually configure the `arrow-libs` repository you can run [these](https://github.com/Paradigm4/extra-scidb-libs/blob/master/install.sh#L62-L65) commands manually or, alternatively, follow the Apache Arrow [instructions](https://arrow.apache.org/install/).

**Comment by ksens** [comment]
@rvernica 

Thanks for the note -- I was able to follow instructions in `install.sh` and get arrow 16. 

However I am running into a host of issues on my customer deployment:

- #26 
- #31 
- shim does not start automatically on server restart

I will ping you to find a time to demonstrate the issues live over a TCon. 

PS: I have a temporary workaround on the customer system (i.e. the customer system is operational) -- we can find a convenient time sometime this week.

**Comment by rvernica** [comment]
I think this is now resolved, right? We should follow-up individually on the related issues listed above.

**Comment by ksens** [comment]
One pending edit -- please update the Manual install portion of the docs to point to the relevant arrow install instructions.
