### ISSUE TITLE
Shim package built incorrectly

### ISSUE THREAD

**Issue by apoliakov** [Paradigm4/extra-scidb-libs#4]
The shim that comes as part of this package does not return the version properly. This does not work:
```
curl -f -s http://localhost:8080/version 
```
It's supposed to return "18.1"

**Comment by apoliakov** [comment]
For example - this standalone shim package does the right thing:
https://github.com/Paradigm4/shim/raw/gh-pages/shim_18.1_amd64.deb

**Comment by JAKinchen** [comment]
Rebuilt the debian package with scidb on the path so the version string is correctly set.

**Comment by apoliakov** [comment]
Could you try checking the rhel package as well?
