### ISSUE TITLE
Build script does not work for RPM at arbitrary working directory

### ISSUE THREAD

**Issue by ksens** [Paradigm4/extra-scidb-libs#9]
In documentation, instructions for building RPM / Deb package say

```sh
./extra-scidb-libs <rpm|deb> <working dir> <result dir> <pkg ver>
```

And example for RPM says:
```sh
./extra-scidb-libs rpm ~ /tmp 0
```

The example works, but running something like the following does not work

```sh
./extra-scidb-libs rpm <any-other-working-dir> /tmp 0
```

I traced this to the fact that `rpmdev-setuptree` sets up the tree at `~`. So the `working directory` argument is superfluous in case of building RPM packages. 

Script should probably complain if any argument but `~` is provided here.

**Comment by rvernica** [comment]
Also related, the `rpm` build does not work for arbitrary version numbers. The version number needs to match the one specified in the [extra-scidb-libs.spec](https://github.com/Paradigm4/extra-scidb-libs/blob/542bf7afa3c1fe09e1cafcde5a4831f58c14c5bf/specs/extra-scidb-libs.spec#L2) file. For example with version `0` one gets:
```bash
> ./extra-scidb-libs.sh rpm ~ `pwd` 0
...
+ SCIDB_INSTALL_PATH=/opt/scidb/18.1
+ QA_RPATHS=18
+ rpmbuild -ba extra-scidb-libs.spec
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.SflqYP
+ umask 022
+ cd /root/rpmbuild/BUILD
+ LANG=C
+ export LANG
+ unset DISPLAY
+ cd /root/rpmbuild/BUILD
+ rm -rf extra-scidb-libs-18.1-1
+ /usr/bin/gzip -dc /root/rpmbuild/SOURCES/extra-scidb-libs-18.1.tar.gz
+ /bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd extra-scidb-libs-18.1-1
/var/tmp/rpm-tmp.SflqYP: line 40: cd: extra-scidb-libs-18.1-1: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.SflqYP (%prep)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.SflqYP (%prep)

```
Notice how `rpmbuild`is looking for the `extra-scidb-libs-18.1-1` directory, that is version `1`, as opposed to version `0` specified as argument.

**Comment by ksens** [comment]
Stale thread. Closing.
